### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by soumallyadev07** [soumallyadev07/MyPortfolio#1]
Add **relevant details** and _improve_ the **README** file

**Comment by ghost** [comment]
Hey @soumallyadev what do you want to be added to the readme file?

**Comment by ghost** [comment]
Hello @soumallyadev07. May I know what exactly needs to b added in the readme?

**Comment by soumallyadev07** [comment]
@KarenEfereyan,  @ShobithMLYA the README needs to include a **basic introduction** of what the project is and what all **technologies** were used to create the same.
I'm assigning you both the issue.

**Comment by ampsteric** [comment]
If not resolved. please assign it to me. I make good READMEs :)

**Comment by ghost** [comment]
@soumallyadev07 will get to it tomorrow

**Comment by ghost** [comment]
@soumallyadev07 I see the current README and I can't seem to figure out what addition I should make. Can you explain better? If not you can just assign it to @ampsteric
